[package]
name = "maze"
version = "0.2.0"
authors = ["Bence Meszaros <bence.me@gmail.com>"]

[dependencies]
rand = "*"
mmap = "*"
num = "*"

[dependencies.threadpool]
version = "*"
features = ["scoped-pool"]
